backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "campaigns"
    label: "Kampaniyalar və Reklamlar"
    folder: "data/campaigns"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Kampaniyanın Adı", name: "title", widget: "string" }
      - { label: "Reklam Banneri (Şəkil)", name: "image", widget: "image" }
      - { label: "Endirim Linki", name: "link", widget: "string", required: false }
      - { label: "Açıqlama / Qısa Mətn", name: "description", widget: "text" }
      - { label: "Kampaniyanın Aktivlik Statusu", name: "active", widget: "boolean", default: true }